### ISSUE TITLE
Touch: Uncaught TypeError: event.detail.sourceEvent.preventDefault is not a function

### ISSUE THREAD

**Issue by pantaluna** [PolymerElements/paper-slider#56]
1. This js error comes up in Chrome on Android touch device as soon as you click somewhere on the slider to make it move to another position. It works fine on Chrome 44.0.2403.157 on Windows7.

Uncaught TypeError: event.detail.sourceEvent.preventDefault is not a function @ paper-slider.html:409

https://github.com/PolymerElements/paper-slider/blob/786197f5986a54b633f8da22ecb7bf8bc4a43df2/paper-slider.html#L410

System: 
- paper-slider v1.0.4 plus fix#41 https://github.com/PolymerElements/paper-slider/issues/41
- Chrome v44.0.2403.133 on Android touch device.

**Comment by blasten** [comment]
That sounds like an issue.    Does `down` have special treatment for mobile @azakus in regard to `sourceEvent`?

**Comment by dfreedm** [comment]
No, that should work. You can also just do `event.preventDefault()`, as I make sure that is forwarded to the sourceEvent.

**Comment by blasten** [comment]
Thanks @azakus  :)

@pantaluna It seems like this was changed after https://github.com/PolymerElements/paper-slider/commit/3665e0a53ac7b9b3e3fbff9174811b51213dd474. I think you might be running an old version because `v1.0.4` isn't using `event.detail.sourceEvent.preventDefault`.   I'm going to close this issue, but feel free to reopen if the problem persists.
